# version: '2'
# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000
#     ports:
#       - 2181:2181
  
#   kafka:
#     image: confluentinc/cp-kafka:6.2.14.amd64
#     depends_on:
#       - zookeeper
#     ports:
#       - 29092:29092
#     environment:
#       KAFKA_BROKER_ID: 1
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://127.0.0.1:29092
#       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#       KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#   kafka_manager:
#     depends_on:
#       - kafka
#     image: deltaprojects/kafka-manager
#     ports:
#       - "9000:9000"
#     environment:
#       ZK_HOSTS: "127.0.0.1:2181"
#       APPLICATION_SECRET: "random-secret"
#       KAFKA_MANAGER_USERNAME: "fraseque"

#       KAFKA_MANAGER_PASSWORD: "fraseque123"

#   kafka-camel-producer:
#     depends_on:
#       - kafka
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: kafka-camel-producer
#     ports:
#       - 8080:8080